### ISSUE TITLE
navigation buttons missing after uninstall

### ISSUE THREAD

**Issue by ghost** [Magisk-Modules-Repo/HideNavBar#100]
After installing on Google pixel 3 android 12 I didn't like it so I uninstalled it from magisk but when the device restarted there were no navigation buttons and cannot seem to enable them from settings. how can I get them back? I can only use gesture navigations but they are difficult to use.

**Comment by DanGLVK** [comment]
> After installing on Google pixel 3 android 12 I didn't like it so I uninstalled it from magisk but when the device restarted there were no navigation buttons and cannot seem to enable them from settings. how can I get them back? I can only use gesture navigations but they are difficult to use.

Try clearing the /data/resource -cache and /data/system/package-cache folder

**Comment by rockyit98** [comment]
"Try clearing the /data/resource -cache and /data/system/package-cache folder"

**Comment by DanGLVK** [comment]
> "Try clearing the /data/resource -cache and /data/system/package-cache folder" do I need root a browser or twrp recovery?

Yes

**Comment by rockyit98** [comment]
> >  
> Try clearing the /data/resource -cache and /data/system/package-cache folder
do I need root a browser or twrp recovery?

**Comment by ghost** [comment]
> > "Try clearing the /data/resource -cache and /data/system/package-cache folder" do I need root a browser or twrp recovery?
> 
> Yes

what do you recommend? I have FX file explorer. 
but I can't find the address.

**Comment by DanGLVK** [comment]
> > > "Try clearing the /data/resource -cache and /data/system/package-cache folder" do I need root a browser or twrp recovery?
> > 
> > 
> > Yes
> 
> what do you recommend? I have FX file explorer. but I can't find the address.

Anything with root access will do, you can find /data in the device's root directory

**Comment by ghost** [comment]
> /data/resource -cache

 has lot of files that named like "data@resource-cache@com.android..."


>data/system/package-cache folder 

has a  singal folder that filled with lot of stuff. what exactly need to be removed? do deleting all will cause further problems?
what happens if I move them in to a New Folder inside the current folder Just incase?

**Comment by DanGLVK** [comment]
> > /data/resource -cache
> 
> has lot of files that named like "data@[resource-cache@com.android](mailto:resource-cache@com.android)..."
> 
> > data/system/package-cache folder
> 
> has a singal folder that filled with lot of stuff. what exactly need to be removed? do deleting all will cause further problems? what happens if I move them in to a New Folder inside the current folder Just incase?

Just delete everything in there, or move them, your choice

**Comment by ghost** [comment]
IT worked. thanks.
