### ISSUE TITLE
Status bar peeking while full screen

### ISSUE THREAD

**Issue by hrldabon** [Magisk-Modules-Repo/HideNavBar#11]
Disable status bar peeking when swiping on bottom or side screen while gaming or using any full screen app. MIUI has a good, imo, way of implementing this.

**Comment by DanGLES3** [comment]
This is outside my control, I cannot change the peeking behaviour

**Comment by DanGLES3** [comment]
At best I may be able to disable peeking for the back gesture but I'm not 
100% sure on that as I'm quite limited
with my overlays
