### ISSUE TITLE
Light theme support

### ISSUE THREAD

**Issue by denyslv** [Magisk-Modules-Repo/HideNavBar#18]
This would be really nice if module supported white theme. Right now pill doesn't change color to black on white background.
Pocophone F1 Reloaded 1.1 Android 11
![Screenshot_20201004-174813_Chrome~2](https://user-images.githubusercontent.com/58297803/95018672-eb109f80-0669-11eb-908e-aa929ed0bcdf.png)
![Screenshot_20201004-174846_Chrome~2](https://user-images.githubusercontent.com/58297803/95018679-f1068080-0669-11eb-8320-eb63d77b7ffd.png)

**Comment by charmsoul** [comment]
Needs to improvise finishing

**Comment by DanGLES3** [comment]
From what I could gather Android 11 directly ties the gesture bar coloring to the navbar (which gets removed by module for obvious reasons), so unfortunately for the time being I'll have to close this issue as there isn't anything that can be done from my side atm


If anyone has any ideas feel free to tell me
