### ISSUE TITLE
Do not hide the navbar/back button when the keyboard is shown

### ISSUE THREAD

**Issue by SleeplessSloth** [Magisk-Modules-Repo/HideNavBar#2]
Without the navbar the keyboard is located way too low and it is somewhat uncomfortable to type. Is there a way to still show the navbar with the keyboard, so that the keyboard would be a bit raised?
![Screenshot_20191203_012732](https://user-images.githubusercontent.com/37976824/70006136-51b9be00-156c-11ea-9fe2-8ca666ed1e36.png)

**Comment by spookymyo** [comment]
I agree! It's too low.

**Comment by thedupin** [comment]
I personally installed the module exactly for removing totally. In this case I increase the height of the keyboard on it settings. Every keyboard has it.

But could have a 2 option while installing and all.

**Comment by SleeplessSloth** [comment]
The deal with increasing the height of the keyboard in the settings is that the spacebar and enter keys are still way too low and our of the comfortable typing zone, at least for me

**Comment by Madis0** [comment]
For me it isn't too low, but the gestures are interfering with the keyboard, especially the assistant action.

**Comment by DanGLES3** [comment]
> Really awesome module, thanks! The only issue I have is that without the navbar the keyboard is located too low and it is somewhat uncomfortable to type. Is there a way to still show the navbar with the keyboard, so that the keyboard would be a bit raised?
> ![Screenshot_20191203_012732](https://user-images.githubusercontent.com/37976824/70006136-51b9be00-156c-11ea-9fe2-8ca666ed1e36.png)

my module's sole purpose was to remove the navbar entirely, if you still want it on the keyboard you should perhaps use the immersive gestures module

**Comment by DanGLES3** [comment]
> I personally installed the module exactly for removing totally. In this case I increase the height of the keyboard on it settings. Every keyboard has it.
> 
> But could have a 2 option while installing and all.

i would rather not as then my module could be percieved as a copy of the immersive gestures module

**Comment by DanGLES3** [comment]
> For me it isn't too low, but the gestures are interfering with the keyboard, especially the assistant action.
> 
> Could the module just remove the gestures when a keyboard is shown? Keeping only the side back gesture active.

well the 3.0 should have addresed the issue by slightly lowering the trigger area, i could probably make it even smaller but that might break the gestures, also i can't selectively disable gestures

**Comment by Madis0** [comment]
> > For me it isn't too low, but the gestures are interfering with the keyboard, especially the assistant action.
> > Could the module just remove the gestures when a keyboard is shown? Keeping only the side back gesture active.
> 
> well the v3 update should have addresed the issue by slightly lowering the trigger area, i could probably make it even smaller but that might break the gestures, also i can't selectively disable gestures (that is outside my control)

Using v6 with Fleksy and it is still bad, swiping up triggers either assistant or home (if assistant is disabled). 

Wouldn't "breaking the gestures" be the same as disabling them? If yes, I would suggest trying that.

**Comment by DanGLES3** [comment]
> > > For me it isn't too low, but the gestures are interfering with the keyboard, especially the assistant action.
> > > Could the module just remove the gestures when a keyboard is shown? Keeping only the side back gesture active.
> > 
> > 
> > well the v3 update should have addresed the issue by slightly lowering the trigger area, i could probably make it even smaller but that might break the gestures, also i can't selectively disable gestures (that is outside my control)
> 
> Using v6 with Fleksy and it is still bad, swiping up triggers either assistant or home (if assistant is disabled).
> 
> Wouldn't "breaking the gestures" be the same as disabling them? If yes, I would suggest trying that.
 by breaking the gestures i mean they wouldn't work at all

**Comment by DanGLES3** [comment]
> > > For me it isn't too low, but the gestures are interfering with the keyboard, especially the assistant action.
> > > Could the module just remove the gestures when a keyboard is shown? Keeping only the side back gesture active.
> > 
> > 
> > well the v3 update should have addresed the issue by slightly lowering the trigger area, i could probably make it even smaller but that might break the gestures, also i can't selectively disable gestures (that is outside my control)
> 
> Using v6 with Fleksy and it is still bad, swiping up triggers either assistant or home (if assistant is disabled).
> 
> Wouldn't "breaking the gestures" be the same as disabling them? If yes, I would suggest trying that.

by breaking i mean the gestures would completely stop working (everywhere)

**Comment by Madis0** [comment]
How about showing a bar as tall as the normal built-in one when the keyboard is active? 

Would solve the gesture issue and would not look the same as default/immersive gestures module.

**Comment by DanGLES3** [comment]
> How about showing a bar as tall as the normal built-in one when the keyboard is active? Possibly just black/colored/transparent, no white line needed.
> 
> Would solve the gesture issue and would not look the same as default/immersive gestures module.

that's beyond what i can do, i can only control the stock navbar values and the keyboard navbar and pill are both tied to the same value (navbar_frame_height)

**Comment by DanGLES3** [comment]
> For me it isn't too low, but the gestures are interfering with the keyboard, especially the assistant action.
> 
> Could the module just remove the gestures when a keyboard is shown? Keeping only the side back gesture active.

what's your keyboard app?, if it's gboard then there is a module that can add a small bar underneath gboard to reduce conflict with gestures

**Comment by SleeplessSloth** [comment]
> use the immersive gestures module
The deal with that is that the gesture bar hurts readability really bad and your solution is way better in that regard.
> there is a module that can add a small bar underneath gboard
What's that module called?

**Comment by Madis0** [comment]
I'm using Fleksy and I forgot it already has an option for this! Settings > Advanced > Change keyboard insets > Bottom.

**Comment by DanGLES3** [comment]
> I'm using Fleksy and I forgot it already has an option for this! Settings > Advanced > Change keyboard insets > Bottom.

[navbar-space.zip](https://github.com/Magisk-Modules-Repo/HideNavBar/files/4014420/navbar-space.zip)


> > use the immersive gestures module
> 
> The deal with that is that the gesture bar hurts readability really bad and your solution is way better in that regard.
> 
> > there is a module that can add a small bar underneath gboard
> 
> What's that module called?

[navbar-space.zip](https://github.com/Magisk-Modules-Repo/HideNavBar/files/4014422/navbar-space.zip)

**Comment by DanGLES3** [comment]
> > use the immersive gestures module
> 
> The deal with that is that the gesture bar hurts readability really bad and your solution is way better in that regard.
> 
> > there is a module that can add a small bar underneath gboard
> 
> What's that module called?

[navbar-space.zip](https://github.com/Magisk-Modules-Repo/HideNavBar/files/4014424/navbar-space.zip)

**Comment by SleeplessSloth** [comment]
That's exactly what I was looking for. Works great in combination with our module. Thanks a lot!
