### ISSUE TITLE
Immersive Pill + Default Spacing under the Keyboard and youtube videos

### ISSUE THREAD

**Issue by andris155** [Magisk-Modules-Repo/HideNavBar#23]
The pill sometimes does not disappear when I rotate phone for the full screen YouTube video view.
Android 11
![InkedScreenshot_20201130-210112_LI](https://user-images.githubusercontent.com/8324198/100658675-c0805180-334f-11eb-9ac6-e1965d271e10.jpg)

**Comment by DanGLES3** [comment]
That's an Youtube app bug
