### ISSUE TITLE
Keyboard is blocked by invisible navigation bar in landscape mode

### ISSUE THREAD

**Issue by raphtlw** [Magisk-Modules-Repo/HideNavBar#24]
I cannot tap the spacebar and the other buttons surrounding it.

![Screenshot_20201203-152604.png](https://user-images.githubusercontent.com/47694127/100977403-e7bb6680-357b-11eb-9b1e-bf697ca8f64d.png)

**Comment by DanGLES3** [comment]
Could you give me some extra info? What device? ROM? Any specific apps where this happens?

**Comment by raphtlw** [comment]
> Could you give me some extra info? What device? ROM? Any specific apps where this happens?

It only happens in landscape mode, and happens in any app. Pixel 3, stock Pixel ROM.

**Comment by DanGLES3** [comment]
> > Could you give me some extra info? What device? ROM? Any specific apps where this happens?
> 
> It only happens in landscape mode, and happens in any app. Pixel 3, stock Pixel ROM.

Could you record a video demonstrating the issue?, I'm not sure what could exactly be causing this

**Comment by raphtlw** [comment]
> > > Could you give me some extra info? What device? ROM? Any specific apps where this happens?
> > 
> > It only happens in landscape mode, and happens in any app. Pixel 3, stock Pixel ROM.
> 
> Could you record a video demonstrating the issue?, I'm not sure what could exactly be causing this

here
https://youtu.be/Jq_06Ux7o2Q

**Comment by DanGLES3** [comment]
Could you tell me if this also happens in immersive mode with small keyboard bar?

**Comment by raphtlw** [comment]
UPDATE: The issue has been solved in the latest version of the module.
