### ISSUE TITLE
The keyboard height setting does not work after installed the module

### ISSUE THREAD

**Issue by hnzzmyr** [Magisk-Modules-Repo/HideNavBar#25]
When installing the module I setted fullscreen gesture  and android default keyboard height, but actually the keyboard has a low height. Just like the screenshot.
Pixel 3, android 11. The latest system version, and module version is 8.1
Thank you for writing this module.
![Screenshot_20201204-130325](https://user-images.githubusercontent.com/49651968/101124267-a5546100-3631-11eb-940d-9dec96883edb.png)

**Comment by DanGLES3** [comment]
You mean the option on gboard to change the keyboard height doesn't work? That's odd, did you try perhaps clearing its data?

**Comment by hnzzmyr** [comment]
I tried again and found it's just a misunderstanding. Now it works very well. Thanks a lot.
