### ISSUE TITLE
Pixel5,When using the module, the video anti-shake mode cannot be selected

### ISSUE THREAD

**Issue by JimChan96** [Magisk-Modules-Repo/HideNavBar#26]
Device: Google pixel 5
System: Android 11 RQ1A.201205.011
Google camera 8.1.101.345648084
Magisk canary 201101

![微信图片编辑_20201214140609](https://user-images.githubusercontent.com/24699260/102046663-b4e45e80-3e16-11eb-823f-1b1efe4c248f.jpg)
![微信图片编辑_20201214140701](https://user-images.githubusercontent.com/24699260/102046666-b6ae2200-3e16-11eb-8a7b-6e9d848d0c9b.jpg)

**Comment by jedivulcan** [comment]
Same on Pixel 4a. Lot of these fill the logcat. 

12-14 01:50:24.194 940/20974 E/android.hardware.neuralnetworks@1.3-service-qti: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/listener_android.c:251::error: -2147482611: 0 == (nErr = __QAIC_HEADER(adsp_listener_next2)( ctx, nErr, 0, 0, &ctx, &handle, &sc, inBufs, inBufsLen, &inBufsLenReq))

**Comment by DanGLES3** [comment]
Honestly I don't know why Gcam dislikes hiding the navbar so much, currently there isn't anything I can do as I'm unable to find a fix for it

**Comment by JimChan96** [comment]
@DanGLES3 Maybe can consider adding the function of whether different applications are full screen, thanks for making this module

**Comment by DanGLES3** [comment]
> @DanGLES3 Maybe can consider adding the function of whether different applications are full screen, thanks for making this module
> 
> 

Unfortunately that's not possible to do withing the limitations of how my module functions, only way this would be somewhat possible would be to make a new overlay (instead of replacing the stock ones) and then have an automation tool like tasker set it on/off depending on the app
