### ISSUE TITLE
Pixel5 issue

### ISSUE THREAD

**Issue by Funny-Bunny** [Magisk-Modules-Repo/HideNavBar#27]
On my Pixel 5 running stock Android 11 rooted with Magisk (latest canary) no matter the options I choose when I install the latest version of this module, the Camera app become hella sluggish, slow when changing from different modes (portrait, video, etc). The app's controls like for instance the stabilization option from the video recording screen does nothing. I'll link a screenshot of how the options should look like that the module breaks.
![Screenshot_20201217-191141](https://user-images.githubusercontent.com/14282709/102519969-d86c0b00-409b-11eb-9fa9-b0f8d4674692.png)

**Comment by Funny-Bunny** [comment]
Here's a screen record to show how the app is affected.

**Comment by DanGLES3** [comment]
Already mentioned this in a previous issue, but in short idk why Google Camera dislikes hiding the navbar so much and currently there is nothing I can do about it, this issue is outside my control
