### ISSUE TITLE
Hiding status bar on Android 11

### ISSUE THREAD

**Issue by LaySoft** [Magisk-Modules-Repo/HideNavBar#36]
This module supports hiding status bar under Android 11? I tried it with crDroid 7.3 Custom ROM on OnePlus 5T, but it doesn't work for me.

**Comment by DanGLES3** [comment]
Can't you just use something like the systemui tuner app to enable systemwide status bar Immersive mode? That should achieve something similar to what you want

**Comment by LaySoft** [comment]
All immersive mode apps (like this: https://play.google.com/store/apps/details?id=com.ivianuu.immersivemodemanager&hl=en&gl=US)  doesn't work on Android 11. That's why I thought your module solved the problem.

**Comment by DanGLES3** [comment]
> All immersive mode apps (like this: https://play.google.com/store/apps/details?id=com.ivianuu.immersivemodemanager&hl=en&gl=US)  doesn't work on Android 11. That's why I thought your module solved the problem.

To be fair I couldn't fix this even if I wanted to, hiding the status bar the same way I hide the navigation bar would most likely just break things pretty badly, also odd that those apps aren't working for you as I've heard them working for some people on Android 11

**Comment by pc00per** [comment]
Overscan(which is the reason you hiding works below A10) borked by google since A11. Those apps you mention, use overscaning to give status bar. Now you can't.

**Comment by DanGLES3** [comment]
> Overscan(which is the reason status bar hiding works below A10) borked by google since A11. Those apps you mention, use overscaning to hide status bar. Now you can't.

Tbh i don't think they were using overscan, but what they used to did break on A11

There used to be a global policy that controled hiding the status and navigation bar (they'd show up again if swiped down/up) and that policy was removed on A11
