### ISSUE TITLE
The position of the return gesture icon is abnormal

### ISSUE THREAD

**Issue by VectorZhao** [Magisk-Modules-Repo/HideNavBar#37]
device ：oneplus 5
OS：LineageOS 18.1 Android 11
When I use return gesture, the position where the finger touches the screen is always lower than the position of the return gesture animation.

**Comment by DanGLES3** [comment]
As far as I'm aware this is intentional behavior on Android, correct me if I'm wrong 

https://github.com/aosp-mirror/platform_frameworks_base/commit/09f17b7988a99972ac8abf16c44abf02c4637f94
