### ISSUE TITLE
Gesture swipe up from bottom disabled

### ISSUE THREAD

**Issue by baocaosu** [Magisk-Modules-Repo/HideNavBar#38]
My device Asus ROG phone 5
I chose Immersive - Hide the pill... All worked as I expected, but the gesture swipe up from bottom to go to the desktop is disabled, swipe up and nothing happend 
Sorry, I need your help but I didnot find other way to contact you

**Comment by DanGLES3** [comment]
Unfortunately ASUS broke the ability to hide the navbar while keeping the gestures in their stock OS, there currently isn't much i can do about that

**Comment by baocaosu** [comment]
Thank you, dev. I will deal with it.
