### ISSUE TITLE
'0' key of lockscreen keypad cut off by fingerprint sensor on OnePlus Phones

### ISSUE THREAD

**Issue by KyleGospo** [Magisk-Modules-Repo/HideNavBar#4]
May need to add some padding to the bottom of the lockscreen pinpad to resolve, currently the lack of a navbar pushes it low enough that the '0' key [clips with the fingerprint sensor area](https://i.imgur.com/2bKL1Rd.jpg), making it hard to press.

**Comment by DanGLES3** [comment]
i'll see what i can do but i'm not sure if i'm able to add padding to the pinpad, i'm also not sure how well this would work on other devices as it may move the pinpad way too close to the clock

**Comment by DanGLES3** [comment]
Also, don't Oneplus devices already have the option to hide the navbar?

**Comment by KyleGospo** [comment]
> 
> 
> Also, don't Oneplus devices already have the option to hide the navbar?

Yes, although with a very different gesture setup. Your solution works much better.

**Comment by DanGLES3** [comment]
> > Also, don't Oneplus devices already have the option to hide the navbar?
> 
> Yes, although with a very different gesture setup. Your solution works much better.

i'll see what i can do, i may need to include a special overlay just for Oneplus devices, could you kindly send me the systemui.apk from your device?

**Comment by KyleGospo** [comment]
Here you are, and thanks again!
https://drive.google.com/file/d/133zglT89pNcaFf-HzTdnsXO0OUDl8OpG/view?usp=sharing

**Comment by DanGLES3** [comment]
> Here you are, and thanks again!
> https://drive.google.com/file/d/133zglT89pNcaFf-HzTdnsXO0OUDl8OpG/view?usp=sharing

**Comment by DanGLES3** [comment]
> > Here you are, and thanks again!
> > https://drive.google.com/file/d/133zglT89pNcaFf-HzTdnsXO0OUDl8OpG/view?usp=sharing

[test-signed2.zip](https://github.com/Magisk-Modules-Repo/HideNavBar/files/4014430/test-signed2.zip)

try this

**Comment by KyleGospo** [comment]
No change on my phone, same spacing.

**Comment by DanGLES3** [comment]
i'll have to put this issue on hold, the padding is controlled by a layout value so it makes it extremely difficult for me to modify it using an overlay since, once i figure something out i'll be sure to post here
