### ISSUE TITLE
Menu corruption after dismissing keyboard on fennic/icecat/firefox

### ISSUE THREAD

**Issue by Schroedingers-Hat** [Magisk-Modules-Repo/HideNavBar#40]
First of all, thanks so much. I love the immersive gestures but the black bar was driving me insane.

I have a problem on a remi note 8 running lineage 17.1 where firefox base browsers leave the menu visible if I type anything into the adress bar.

This is after that menu is dismissed, and I can interact with the page, Rotating the screen  leaves it up but resized. Changing activities makes it correctly dismiss.

![Screenshot_20210415-221056_Fennec](https://user-images.githubusercontent.com/788702/114867264-e8241200-9e37-11eb-9e3a-0db4000ea9fa.png)

it's the same on immersive and fullscreen.

**Comment by DanGLES3** [comment]
Unfortunately this is an app issue, nothing much i can do on my side

**Comment by DanGLES3** [comment]
Unfortunately this is an application bug, not much i can do on the matter
