### ISSUE TITLE
Dismiss keyboard and change keyboard icons sometimes get stuck on AOD

### ISSUE THREAD

**Issue by Aluminite** [Magisk-Modules-Repo/HideNavBar#41]
I'm using a Pixel 3a XL, running the latest stock ROM.
In some apps, notably the stock messages app and Snapchat, if I open the keyboard then press the power button, the icons on the bottom to dismiss the keyboard and change to a different keyboard get stuck on the always on display.
I've added a video to help demonstrate. This does not happen when the module is disabled.

https://user-images.githubusercontent.com/10791181/115647778-6a0db280-a2f2-11eb-8424-42741ba9686c.mp4

**Comment by DanGLES3** [comment]
I see, unfortunately AOD is known to be finicky when it comes to a hidden navbar, I'm not sure how to fix this issue at the moment
