### ISSUE TITLE
Restore back gesture

### ISSUE THREAD

**Issue by sudanking** [Magisk-Modules-Repo/HideNavBar#43]
I tried to disable back gesture but I couldn't enabled it again. I tried to reinstall module with not allow disabling gesture but that also didn't fix it.
Any suggestions?

**Comment by DanGLES3** [comment]
What's your Android version?

**Comment by DanGLES3** [comment]
> I tried to disable back gesture but I couldn't enabled it again. I tried to reinstall module with not allow disabling gesture but that also didn't fix it.
> Any suggestions?

As stated in the installation's disclaimer to reenable the back gesture simply change the back gesture sensitivity in your phone's gesture settings

**Comment by sudanking** [comment]
Thanks for your reply...
But I don't have such settings in my Oxygen OS (OnePlus 7 pro)

**Comment by DanGLES3** [comment]
> Thanks for your reply...
> But I don't have such settings in my Oxygen OS (OnePlus 7 pro)

Download the module again, install it, reboot, then uninstall it, i've added some uninstall logic to automatically reenable gestures on module uninstallation

**Comment by sudanking** [comment]
I tried with no luck.... I installed 9.1....reboot... remove module.... Back gesture still not working.

**Comment by DanGLES3** [comment]
> I tried with no luck.... I installed 9.1....reboot... remove module.... Back gesture still not working.

Alright, try installing 9.2 and selecting no to disabling back gesture

**Comment by sudanking** [comment]
Yeees... It is back now.
Thanks for great module and support

**Comment by DanGLES3** [comment]
> Yeees... It is back now.
> Thanks for great module and support

Thank you for your feedback, thanks to you i avoided causing issues to more users
