### ISSUE TITLE
Releases not in github

### ISSUE THREAD

**Issue by fusionneur** [Magisk-Modules-Repo/HideNavBar#44]
How do i download zip?

**Comment by DanGLES3** [comment]
I'd had stopped pushing updates on GitHub as they're available on the Magisk manager as well, any particular reason why you need GitHub releases?

**Comment by fusionneur** [comment]
I opened the issue because there is no option to re-install module in the "Installed" section in magisk. I realized afterwards, I can actually search for the module in magisk manager and was able to reinstall it from here.

i wanted to reinstall the module because on my OP 7t pro, this module buggs when detecting volume up/down buttons and I have to press fast or else it quickly timeouts and fails. I accidentally pressed volume up when asked to disable back gesture on left side, which i didn't want. So maybe it is worth opening another issue for the detection bug instead.

**Comment by CaseOf** [comment]
Hello,
Now that @topjohnwu has removed built-in repository in Magisk, would you add zip in releases?
