### ISSUE TITLE
Please add a middle option

### ISSUE THREAD

**Issue by Himanshufulmali** [Magisk-Modules-Repo/HideNavBar#46]
Sir big fan of your work but when we apply the module for full screen gesture, while typing gestures do not behave as they should, it switch tabs while typing, it goes to last app, sometimes home (while texting). it's really annoying while typing.
So I'm requesting a space  between keyboard and pill or navbat which is less than stock android but a bit more than your fullscreen  so that gestures do not get triggered while texting, it'll be a great help.

**Comment by DanGLES3** [comment]
You can achieve that with immersive+hide pill+small keyboard bar

**Comment by Himanshufulmali** [comment]
Thanks a lot sir, i didn't try immersive option yet, will try and let you know.
