### ISSUE TITLE
This module works on Oxygen OS!

### ISSUE THREAD

**Issue by kirankunigiri** [Magisk-Modules-Repo/HideNavBar#47]
Hi! Thanks so much for making this mod. I just installed this on my OnePlus 8T+ running the latest Oxygen OS 11 and it works perfectly! I used this configuration: **Immersive (Without the Pill + Default Spacing under the Keyboard)**

You can update your description so that people know it works, at least on the 8T.

**Comment by DanGLES3** [comment]
Does regular immersive work (without hiding the pill)? If so could you provide me a screenshot?

**Comment by kirankunigiri** [comment]
I'll check right now. Is there anyway to change the settings without uninstalling and reinstalling?

**Comment by DanGLES3** [comment]
Well, I've decided to update the disclaimer to more broadly handle issues, so if any issues happen or get fixed I won't need to constantly update the disclaimer

Anyway thanks for your report
