### ISSUE TITLE
Trigger areas for back gesture

### ISSUE THREAD

**Issue by FPSUsername** [Magisk-Modules-Repo/HideNavBar#50]
After moving from MIUI to an AOSP rom (YAAP), I noticed that the AOSP gestures trigger on the complete height of the side of the display. This is super annoying with apps that have a sidebar that you can slide open (examples are Boost for reddit and Telegram).

It would be nice to have an option to ignore the back gesture when you swipe in the top ⅓ area of the display (also in landscape), so that you can still trigger the swipe to open the sidebar of the app.

The only workaround, which feels unnatural to use, is to swipe down from the edge, and then towards the other edge of the screen to open it.

**Comment by DanGLES3** [comment]
Unfortunately that's not possible to do with Magisk module, the most that can done is disabling it for one side altogether (on Android 11 and up)

Also another workaround is briefly long pressing then swiping (significantly less awkward than your workaround)

**Comment by DanGLES3** [comment]
> After moving from MIUI to an AOSP rom (YAAP), I noticed that the AOSP gestures trigger on the complete height of the side of the display. This is super annoying with apps that have a sidebar that you can slide open (examples are Boost for reddit and Telegram).
> 
> It would be nice to have an option to ignore the back gesture when you swipe in the top ⅓ area of the display (also in landscape), so that you can still trigger the swipe to open the sidebar of the app.
> 
> The only workaround, which feels unnatural to use, is to swipe down from the edge, and then towards the other edge of the screen to open it.

Unfortunately that's not possible to do with a Magisk module, the most that can done is disabling it for one side altogether (on Android 11 and up)

Also another workaround is briefly long pressing then swiping (significantly less awkward than your workaround)

**Comment by FPSUsername** [comment]
That is unfortunate. The other workaround works as well, but it's a really slow process compared to only swiping.
