### ISSUE TITLE
Newest version doesn't display options when installing. 

### ISSUE THREAD

**Issue by lividhen** [Magisk-Modules-Repo/HideNavBar#52]
The latest release doesn't display the options when installing. It still checks for volume key presses, and changes the settings, but you can't see what your selecting.

**Comment by DanGLES3** [comment]
What's your system language?

**Comment by DanGLES3** [comment]
> The latest release doesn't display the options when installing. It still checks for volume key presses, and changes the settings, but you can't see what your selecting. 

What's your system language? Device? 

Tested here and it's good even on non supported languages (Falls back to English)

Save the module install logs (tap the save icon at the top after the module finishes installing) and send the text file to me ASAP

**Comment by lividhen** [comment]
System language is US English. Device is SM-T350 (running crdroid 7.7, so I don't thing the model matters much)

<details>
    <summary>Installer log:</summary> 

```
- Copying zip to temp directory
- Installing Fullscreen_Immersive_Gestures_(Q-S)-v9.5(31).zip
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
*************************************
 Fullscreen/Immersive Gestures (Q-S) 
 by DanGLES3 
*************************************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
*******************
 Powered by Magisk 
*******************
/data/user/0/com.topjohnwu.magisk/cache/flash/update-binary: /data/adb/modules_update/HideNavBar/customize.sh: line 1: n##########################################################################################: not found
**************************************
*   MMT Extended by Zackptg5 @ XDA   *
**************************************
 
- Extracting module files
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: LICENSE
   creating: Lang/
   creating: Lang/en/
  inflating: Lang/en/en1.txt
  inflating: Lang/en/en2.txt
  inflating: Lang/en/en3.txt
  inflating: Lang/en/en4.txt
  inflating: Lang/en/en5.txt
  inflating: Lang/en/en6.txt
  inflating: Lang/en/en7.txt
   creating: Lang/es/
  inflating: Lang/es/es1.txt
  inflating: Lang/es/es2.txt
  inflating: Lang/es/es3.txt
  inflating: Lang/es/es4.txt
  inflating: Lang/es/es5.txt
  inflating: Lang/es/es6.txt
  inflating: Lang/es/es7.txt
   creating: Lang/pt/
  inflating: Lang/pt/pt1.txt
  inflating: Lang/pt/pt2.txt
  inflating: Lang/pt/pt3.txt
  inflating: Lang/pt/pt4.txt
  inflating: Lang/pt/pt5.txt
  inflating: Lang/pt/pt6.txt
  inflating: Lang/pt/pt7.txt
   creating: Mods/
   creating: Mods/DBGQ/
  inflating: Mods/DBGQ/system.prop
   creating: Mods/HP/
  inflating: Mods/HP/pillhide.apk
   creating: Mods/IMQ/
   creating: Mods/IMQ/NavigationBarModeGestural/
  inflating: Mods/IMQ/NavigationBarModeGestural/NavigationBarModeGesturalOverlay.apk
   creating: Mods/IMQ/NavigationBarModeGesturalExtraWideBack/
  inflating: Mods/IMQ/NavigationBarModeGesturalExtraWideBack/NavigationBarModeGesturalOverlayExtraWideBack.apk
   creating: Mods/IMQ/NavigationBarModeGesturalNarrowBack/
  inflating: Mods/IMQ/NavigationBarModeGesturalNarrowBack/NavigationBarModeGesturalOverlayNarrowBack.apk
   creating: Mods/IMQ/NavigationBarModeGesturalWideBack/
  inflating: Mods/IMQ/NavigationBarModeGesturalWideBack/NavigationBarModeGesturalOverlayWideBack.apk
   creating: Mods/IMQDS/
   creating: Mods/IMQDS/NavigationBarModeGestural/
  inflating: Mods/IMQDS/NavigationBarModeGestural/NavigationBarModeGesturalOverlay.apk
   creating: Mods/IMQDS/NavigationBarModeGesturalExtraWideBack/
  inflating: Mods/IMQDS/NavigationBarModeGesturalExtraWideBack/NavigationBarModeGesturalOverlayExtraWideBack.apk
   creating: Mods/IMQDS/NavigationBarModeGesturalNarrowBack/
  inflating: Mods/IMQDS/NavigationBarModeGesturalNarrowBack/NavigationBarModeGesturalOverlayNarrowBack.apk
   creating: Mods/IMQDS/NavigationBarModeGesturalWideBack/
  inflating: Mods/IMQDS/NavigationBarModeGesturalWideBack/NavigationBarModeGesturalOverlayWideBack.apk
   creating: Mods/IMQS/
   creating: Mods/IMQS/NavigationBarModeGestural/
  inflating: Mods/IMQS/NavigationBarModeGestural/NavigationBarModeGesturalOverlay.apk
   creating: Mods/IMQS/NavigationBarModeGesturalExtraWideBack/
  inflating: Mods/IMQS/NavigationBarModeGesturalExtraWideBack/NavigationBarModeGesturalOverlayExtraWideBack.apk
   creating: Mods/IMQS/NavigationBarModeGesturalNarrowBack/
  inflating: Mods/IMQS/NavigationBarModeGesturalNarrowBack/NavigationBarModeGesturalOverlayNarrowBack.apk
   creating: Mods/IMQS/NavigationBarModeGesturalWideBack/
  inflating: Mods/IMQS/NavigationBarModeGesturalWideBack/NavigationBarModeGesturalOverlayWideBack.apk
   creating: Mods/IMQSDS/
   creating: Mods/IMQSDS/NavigationBarModeGestural/
  inflating: Mods/IMQSDS/NavigationBarModeGestural/NavigationBarModeGesturalOverlay.apk
   creating: Mods/IMQSDS/NavigationBarModeGesturalExtraWideBack/
  inflating: Mods/IMQSDS/NavigationBarModeGesturalExtraWideBack/NavigationBarModeGesturalOverlayExtraWideBack.apk
   creating: Mods/IMQSDS/NavigationBarModeGesturalNarrowBack/
  inflating: Mods/IMQSDS/NavigationBarModeGesturalNarrowBack/NavigationBarModeGesturalOverlayNarrowBack.apk
   creating: Mods/IMQSDS/NavigationBarModeGesturalWideBack/
  inflating: Mods/IMQSDS/NavigationBarModeGesturalWideBack/NavigationBarModeGesturalOverlayWideBack.apk
   creating: Mods/Q/
   creating: Mods/Q/NavigationBarModeGestural/
  inflating: Mods/Q/NavigationBarModeGestural/NavigationBarModeGesturalOverlay.apk
   creating: Mods/Q/NavigationBarModeGesturalExtraWideBack/
  inflating: Mods/Q/NavigationBarModeGesturalExtraWideBack/NavigationBarModeGesturalOverlayExtraWideBack.apk
   creating: Mods/Q/NavigationBarModeGesturalNarrowBack/
  inflating: Mods/Q/NavigationBarModeGesturalNarrowBack/NavigationBarModeGesturalOverlayNarrowBack.apk
   creating: Mods/Q/NavigationBarModeGesturalWideBack/
  inflating: Mods/Q/NavigationBarModeGesturalWideBack/NavigationBarModeGesturalOverlayWideBack.apk
   creating: Mods/QDS/
   creating: Mods/QDS/NavigationBarModeGestural/
  inflating: Mods/QDS/NavigationBarModeGestural/NavigationBarModeGesturalOverlay.apk
   creating: Mods/QDS/NavigationBarModeGesturalExtraWideBack/
  inflating: Mods/QDS/NavigationBarModeGesturalExtraWideBack/NavigationBarModeGesturalOverlayExtraWideBack.apk
   creating: Mods/QDS/NavigationBarModeGesturalNarrowBack/
  inflating: Mods/QDS/NavigationBarModeGesturalNarrowBack/NavigationBarModeGesturalOverlayNarrowBack.apk
   creating: Mods/QDS/NavigationBarModeGesturalWideBack/
  inflating: Mods/QDS/NavigationBarModeGesturalWideBack/NavigationBarModeGesturalOverlayWideBack.apk
  inflating: README.md
   creating: common/
   creating: common/addon/
   creating: common/addon/Volume-Key-Selector/
  inflating: common/addon/Volume-Key-Selector/README.md
  inflating: common/addon/Volume-Key-Selector/a
  inflating: common/addon/Volume-Key-Selector/install.sh
   creating: common/addon/Volume-Key-Selector/tools/
   creating: common/addon/Volume-Key-Selector/tools/arm/
  inflating: common/addon/Volume-Key-Selector/tools/arm/keycheck
   creating: common/addon/Volume-Key-Selector/tools/x86/
  inflating: common/addon/Volume-Key-Selector/tools/x86/keycheck
  inflating: common/install.sh
  inflating: customize.sh
  inflating: module.prop
  inflating: service.sh
 
- Running Addons -
  Running Volume-Key-Selector...
- Removing old files
- Installing
cat: can't open '/data/adb/modules_update/HideNavBar/Lang//1.txt': No such file or directory
cat: can't open '/data/adb/modules_update/HideNavBar/Lang//2.txt': No such file or directory
Volume key not detected. Try again
Volume key not detected. Trying keycheck method
cat: can't open '/data/adb/modules_update/HideNavBar/Lang//3.txt': No such file or directory
cat: can't open '/data/adb/modules_update/HideNavBar/Lang//4.txt': No such file or directory
Terminated
cat: can't open '/data/adb/modules_update/HideNavBar/Lang//5.txt': No such file or directory
Deleted 1 rows
Deleted 1 rows
find: /system/overlay: No such file or directory
cp: can't stat '/data/adb/modules_update/HideNavBar/Mods/a/*': No such file or directory
mv: can't rename '/data/adb/modules_update/HideNavBar/system/system/*': No such file or directory
   Installing for arm SDK 30 device...
 
- Setting Permissions
rmdir: '/data/adb/modules_update/HideNavBar': Directory not empty
- Done
```

</details>

**Comment by DanGLES3** [comment]
This is really weird, your device is returning no language whatsoever

Could you try changing your language to like British English then back to English US? 

Odd as English here works perfectly fine

**Comment by DanGLES3** [comment]
> System language is US English. Device is SM-T350 (running crdroid 7.7, so I'm not sure the model matters much)
> 
> <details>
>     <summary>Installer log:</summary> 
> 
> ```
> - Copying zip to temp directory
> - Installing Fullscreen_Immersive_Gestures_(Q-S)-v9.5(31).zip
> - Device is system-as-root
> Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
>   inflating: module.prop
> *************************************
>  Fullscreen/Immersive Gestures (Q-S) 
>  by DanGLES3 
> *************************************
> Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
>   inflating: customize.sh
> *******************
>  Powered by Magisk 
> *******************
> /data/user/0/com.topjohnwu.magisk/cache/flash/update-binary: /data/adb/modules_update/HideNavBar/customize.sh: line 1: n##########################################################################################: not found
> **************************************
> *   MMT Extended by Zackptg5 @ XDA   *
> **************************************
>  
> - Extracting module files
> Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
>   inflating: LICENSE
>    creating: Lang/
>    creating: Lang/en/
>   inflating: Lang/en/en1.txt
>   inflating: Lang/en/en2.txt
>   inflating: Lang/en/en3.txt
>   inflating: Lang/en/en4.txt
>   inflating: Lang/en/en5.txt
>   inflating: Lang/en/en6.txt
>   inflating: Lang/en/en7.txt
>    creating: Lang/es/
>   inflating: Lang/es/es1.txt
>   inflating: Lang/es/es2.txt
>   inflating: Lang/es/es3.txt
>   inflating: Lang/es/es4.txt
>   inflating: Lang/es/es5.txt
>   inflating: Lang/es/es6.txt
>   inflating: Lang/es/es7.txt
>    creating: Lang/pt/
>   inflating: Lang/pt/pt1.txt
>   inflating: Lang/pt/pt2.txt
>   inflating: Lang/pt/pt3.txt
>   inflating: Lang/pt/pt4.txt
>   inflating: Lang/pt/pt5.txt
>   inflating: Lang/pt/pt6.txt
>   inflating: Lang/pt/pt7.txt
>    creating: Mods/
>    creating: Mods/DBGQ/
>   inflating: Mods/DBGQ/system.prop
>    creating: Mods/HP/
>   inflating: Mods/HP/pillhide.apk
>    creating: Mods/IMQ/
>    creating: Mods/IMQ/NavigationBarModeGestural/
>   inflating: Mods/IMQ/NavigationBarModeGestural/NavigationBarModeGesturalOverlay.apk
>    creating: Mods/IMQ/NavigationBarModeGesturalExtraWideBack/
>   inflating: Mods/IMQ/NavigationBarModeGesturalExtraWideBack/NavigationBarModeGesturalOverlayExtraWideBack.apk
>    creating: Mods/IMQ/NavigationBarModeGesturalNarrowBack/
>   inflating: Mods/IMQ/NavigationBarModeGesturalNarrowBack/NavigationBarModeGesturalOverlayNarrowBack.apk
>    creating: Mods/IMQ/NavigationBarModeGesturalWideBack/
>   inflating: Mods/IMQ/NavigationBarModeGesturalWideBack/NavigationBarModeGesturalOverlayWideBack.apk
>    creating: Mods/IMQDS/
>    creating: Mods/IMQDS/NavigationBarModeGestural/
>   inflating: Mods/IMQDS/NavigationBarModeGestural/NavigationBarModeGesturalOverlay.apk
>    creating: Mods/IMQDS/NavigationBarModeGesturalExtraWideBack/
>   inflating: Mods/IMQDS/NavigationBarModeGesturalExtraWideBack/NavigationBarModeGesturalOverlayExtraWideBack.apk
>    creating: Mods/IMQDS/NavigationBarModeGesturalNarrowBack/
>   inflating: Mods/IMQDS/NavigationBarModeGesturalNarrowBack/NavigationBarModeGesturalOverlayNarrowBack.apk
>    creating: Mods/IMQDS/NavigationBarModeGesturalWideBack/
>   inflating: Mods/IMQDS/NavigationBarModeGesturalWideBack/NavigationBarModeGesturalOverlayWideBack.apk
>    creating: Mods/IMQS/
>    creating: Mods/IMQS/NavigationBarModeGestural/
>   inflating: Mods/IMQS/NavigationBarModeGestural/NavigationBarModeGesturalOverlay.apk
>    creating: Mods/IMQS/NavigationBarModeGesturalExtraWideBack/
>   inflating: Mods/IMQS/NavigationBarModeGesturalExtraWideBack/NavigationBarModeGesturalOverlayExtraWideBack.apk
>    creating: Mods/IMQS/NavigationBarModeGesturalNarrowBack/
>   inflating: Mods/IMQS/NavigationBarModeGesturalNarrowBack/NavigationBarModeGesturalOverlayNarrowBack.apk
>    creating: Mods/IMQS/NavigationBarModeGesturalWideBack/
>   inflating: Mods/IMQS/NavigationBarModeGesturalWideBack/NavigationBarModeGesturalOverlayWideBack.apk
>    creating: Mods/IMQSDS/
>    creating: Mods/IMQSDS/NavigationBarModeGestural/
>   inflating: Mods/IMQSDS/NavigationBarModeGestural/NavigationBarModeGesturalOverlay.apk
>    creating: Mods/IMQSDS/NavigationBarModeGesturalExtraWideBack/
>   inflating: Mods/IMQSDS/NavigationBarModeGesturalExtraWideBack/NavigationBarModeGesturalOverlayExtraWideBack.apk
>    creating: Mods/IMQSDS/NavigationBarModeGesturalNarrowBack/
>   inflating: Mods/IMQSDS/NavigationBarModeGesturalNarrowBack/NavigationBarModeGesturalOverlayNarrowBack.apk
>    creating: Mods/IMQSDS/NavigationBarModeGesturalWideBack/
>   inflating: Mods/IMQSDS/NavigationBarModeGesturalWideBack/NavigationBarModeGesturalOverlayWideBack.apk
>    creating: Mods/Q/
>    creating: Mods/Q/NavigationBarModeGestural/
>   inflating: Mods/Q/NavigationBarModeGestural/NavigationBarModeGesturalOverlay.apk
>    creating: Mods/Q/NavigationBarModeGesturalExtraWideBack/
>   inflating: Mods/Q/NavigationBarModeGesturalExtraWideBack/NavigationBarModeGesturalOverlayExtraWideBack.apk
>    creating: Mods/Q/NavigationBarModeGesturalNarrowBack/
>   inflating: Mods/Q/NavigationBarModeGesturalNarrowBack/NavigationBarModeGesturalOverlayNarrowBack.apk
>    creating: Mods/Q/NavigationBarModeGesturalWideBack/
>   inflating: Mods/Q/NavigationBarModeGesturalWideBack/NavigationBarModeGesturalOverlayWideBack.apk
>    creating: Mods/QDS/
>    creating: Mods/QDS/NavigationBarModeGestural/
>   inflating: Mods/QDS/NavigationBarModeGestural/NavigationBarModeGesturalOverlay.apk
>    creating: Mods/QDS/NavigationBarModeGesturalExtraWideBack/
>   inflating: Mods/QDS/NavigationBarModeGesturalExtraWideBack/NavigationBarModeGesturalOverlayExtraWideBack.apk
>    creating: Mods/QDS/NavigationBarModeGesturalNarrowBack/
>   inflating: Mods/QDS/NavigationBarModeGesturalNarrowBack/NavigationBarModeGesturalOverlayNarrowBack.apk
>    creating: Mods/QDS/NavigationBarModeGesturalWideBack/
>   inflating: Mods/QDS/NavigationBarModeGesturalWideBack/NavigationBarModeGesturalOverlayWideBack.apk
>   inflating: README.md
>    creating: common/
>    creating: common/addon/
>    creating: common/addon/Volume-Key-Selector/
>   inflating: common/addon/Volume-Key-Selector/README.md
>   inflating: common/addon/Volume-Key-Selector/a
>   inflating: common/addon/Volume-Key-Selector/install.sh
>    creating: common/addon/Volume-Key-Selector/tools/
>    creating: common/addon/Volume-Key-Selector/tools/arm/
>   inflating: common/addon/Volume-Key-Selector/tools/arm/keycheck
>    creating: common/addon/Volume-Key-Selector/tools/x86/
>   inflating: common/addon/Volume-Key-Selector/tools/x86/keycheck
>   inflating: common/install.sh
>   inflating: customize.sh
>   inflating: module.prop
>   inflating: service.sh
>  
> - Running Addons -
>   Running Volume-Key-Selector...
> - Removing old files
> - Installing
> cat: can't open '/data/adb/modules_update/HideNavBar/Lang//1.txt': No such file or directory
> cat: can't open '/data/adb/modules_update/HideNavBar/Lang//2.txt': No such file or directory
> Volume key not detected. Try again
> Volume key not detected. Trying keycheck method
> cat: can't open '/data/adb/modules_update/HideNavBar/Lang//3.txt': No such file or directory
> cat: can't open '/data/adb/modules_update/HideNavBar/Lang//4.txt': No such file or directory
> Terminated
> cat: can't open '/data/adb/modules_update/HideNavBar/Lang//5.txt': No such file or directory
> Deleted 1 rows
> Deleted 1 rows
> find: /system/overlay: No such file or directory
> cp: can't stat '/data/adb/modules_update/HideNavBar/Mods/a/*': No such file or directory
> mv: can't rename '/data/adb/modules_update/HideNavBar/system/system/*': No such file or directory
>    Installing for arm SDK 30 device...
>  
> - Setting Permissions
> rmdir: '/data/adb/modules_update/HideNavBar': Directory not empty
> - Done
> ```
> 
> </details>

This is really weird, your device is returning no language whatsoever

Could you try changing your language to like British English then back to English US? 

Odd as English here works perfectly fine

**Comment by DanGLES3** [comment]
> System language is US English. Device is SM-T350 (running crdroid 7.7, so I'm not sure the model matters much)
> 
> <details>
>     <summary>Installer log:</summary> 
> 
> ```
> - Copying zip to temp directory
> - Installing Fullscreen_Immersive_Gestures_(Q-S)-v9.5(31).zip
> - Device is system-as-root
> Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
>   inflating: module.prop
> *************************************
>  Fullscreen/Immersive Gestures (Q-S) 
>  by DanGLES3 
> *************************************
> Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
>   inflating: customize.sh
> *******************
>  Powered by Magisk 
> *******************
> /data/user/0/com.topjohnwu.magisk/cache/flash/update-binary: /data/adb/modules_update/HideNavBar/customize.sh: line 1: n##########################################################################################: not found
> **************************************
> *   MMT Extended by Zackptg5 @ XDA   *
> **************************************
>  
> - Extracting module files
> Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
>   inflating: LICENSE
>    creating: Lang/
>    creating: Lang/en/
>   inflating: Lang/en/en1.txt
>   inflating: Lang/en/en2.txt
>   inflating: Lang/en/en3.txt
>   inflating: Lang/en/en4.txt
>   inflating: Lang/en/en5.txt
>   inflating: Lang/en/en6.txt
>   inflating: Lang/en/en7.txt
>    creating: Lang/es/
>   inflating: Lang/es/es1.txt
>   inflating: Lang/es/es2.txt
>   inflating: Lang/es/es3.txt
>   inflating: Lang/es/es4.txt
>   inflating: Lang/es/es5.txt
>   inflating: Lang/es/es6.txt
>   inflating: Lang/es/es7.txt
>    creating: Lang/pt/
>   inflating: Lang/pt/pt1.txt
>   inflating: Lang/pt/pt2.txt
>   inflating: Lang/pt/pt3.txt
>   inflating: Lang/pt/pt4.txt
>   inflating: Lang/pt/pt5.txt
>   inflating: Lang/pt/pt6.txt
>   inflating: Lang/pt/pt7.txt
>    creating: Mods/
>    creating: Mods/DBGQ/
>   inflating: Mods/DBGQ/system.prop
>    creating: Mods/HP/
>   inflating: Mods/HP/pillhide.apk
>    creating: Mods/IMQ/
>    creating: Mods/IMQ/NavigationBarModeGestural/
>   inflating: Mods/IMQ/NavigationBarModeGestural/NavigationBarModeGesturalOverlay.apk
>    creating: Mods/IMQ/NavigationBarModeGesturalExtraWideBack/
>   inflating: Mods/IMQ/NavigationBarModeGesturalExtraWideBack/NavigationBarModeGesturalOverlayExtraWideBack.apk
>    creating: Mods/IMQ/NavigationBarModeGesturalNarrowBack/
>   inflating: Mods/IMQ/NavigationBarModeGesturalNarrowBack/NavigationBarModeGesturalOverlayNarrowBack.apk
>    creating: Mods/IMQ/NavigationBarModeGesturalWideBack/
>   inflating: Mods/IMQ/NavigationBarModeGesturalWideBack/NavigationBarModeGesturalOverlayWideBack.apk
>    creating: Mods/IMQDS/
>    creating: Mods/IMQDS/NavigationBarModeGestural/
>   inflating: Mods/IMQDS/NavigationBarModeGestural/NavigationBarModeGesturalOverlay.apk
>    creating: Mods/IMQDS/NavigationBarModeGesturalExtraWideBack/
>   inflating: Mods/IMQDS/NavigationBarModeGesturalExtraWideBack/NavigationBarModeGesturalOverlayExtraWideBack.apk
>    creating: Mods/IMQDS/NavigationBarModeGesturalNarrowBack/
>   inflating: Mods/IMQDS/NavigationBarModeGesturalNarrowBack/NavigationBarModeGesturalOverlayNarrowBack.apk
>    creating: Mods/IMQDS/NavigationBarModeGesturalWideBack/
>   inflating: Mods/IMQDS/NavigationBarModeGesturalWideBack/NavigationBarModeGesturalOverlayWideBack.apk
>    creating: Mods/IMQS/
>    creating: Mods/IMQS/NavigationBarModeGestural/
>   inflating: Mods/IMQS/NavigationBarModeGestural/NavigationBarModeGesturalOverlay.apk
>    creating: Mods/IMQS/NavigationBarModeGesturalExtraWideBack/
>   inflating: Mods/IMQS/NavigationBarModeGesturalExtraWideBack/NavigationBarModeGesturalOverlayExtraWideBack.apk
>    creating: Mods/IMQS/NavigationBarModeGesturalNarrowBack/
>   inflating: Mods/IMQS/NavigationBarModeGesturalNarrowBack/NavigationBarModeGesturalOverlayNarrowBack.apk
>    creating: Mods/IMQS/NavigationBarModeGesturalWideBack/
>   inflating: Mods/IMQS/NavigationBarModeGesturalWideBack/NavigationBarModeGesturalOverlayWideBack.apk
>    creating: Mods/IMQSDS/
>    creating: Mods/IMQSDS/NavigationBarModeGestural/
>   inflating: Mods/IMQSDS/NavigationBarModeGestural/NavigationBarModeGesturalOverlay.apk
>    creating: Mods/IMQSDS/NavigationBarModeGesturalExtraWideBack/
>   inflating: Mods/IMQSDS/NavigationBarModeGesturalExtraWideBack/NavigationBarModeGesturalOverlayExtraWideBack.apk
>    creating: Mods/IMQSDS/NavigationBarModeGesturalNarrowBack/
>   inflating: Mods/IMQSDS/NavigationBarModeGesturalNarrowBack/NavigationBarModeGesturalOverlayNarrowBack.apk
>    creating: Mods/IMQSDS/NavigationBarModeGesturalWideBack/
>   inflating: Mods/IMQSDS/NavigationBarModeGesturalWideBack/NavigationBarModeGesturalOverlayWideBack.apk
>    creating: Mods/Q/
>    creating: Mods/Q/NavigationBarModeGestural/
>   inflating: Mods/Q/NavigationBarModeGestural/NavigationBarModeGesturalOverlay.apk
>    creating: Mods/Q/NavigationBarModeGesturalExtraWideBack/
>   inflating: Mods/Q/NavigationBarModeGesturalExtraWideBack/NavigationBarModeGesturalOverlayExtraWideBack.apk
>    creating: Mods/Q/NavigationBarModeGesturalNarrowBack/
>   inflating: Mods/Q/NavigationBarModeGesturalNarrowBack/NavigationBarModeGesturalOverlayNarrowBack.apk
>    creating: Mods/Q/NavigationBarModeGesturalWideBack/
>   inflating: Mods/Q/NavigationBarModeGesturalWideBack/NavigationBarModeGesturalOverlayWideBack.apk
>    creating: Mods/QDS/
>    creating: Mods/QDS/NavigationBarModeGestural/
>   inflating: Mods/QDS/NavigationBarModeGestural/NavigationBarModeGesturalOverlay.apk
>    creating: Mods/QDS/NavigationBarModeGesturalExtraWideBack/
>   inflating: Mods/QDS/NavigationBarModeGesturalExtraWideBack/NavigationBarModeGesturalOverlayExtraWideBack.apk
>    creating: Mods/QDS/NavigationBarModeGesturalNarrowBack/
>   inflating: Mods/QDS/NavigationBarModeGesturalNarrowBack/NavigationBarModeGesturalOverlayNarrowBack.apk
>    creating: Mods/QDS/NavigationBarModeGesturalWideBack/
>   inflating: Mods/QDS/NavigationBarModeGesturalWideBack/NavigationBarModeGesturalOverlayWideBack.apk
>   inflating: README.md
>    creating: common/
>    creating: common/addon/
>    creating: common/addon/Volume-Key-Selector/
>   inflating: common/addon/Volume-Key-Selector/README.md
>   inflating: common/addon/Volume-Key-Selector/a
>   inflating: common/addon/Volume-Key-Selector/install.sh
>    creating: common/addon/Volume-Key-Selector/tools/
>    creating: common/addon/Volume-Key-Selector/tools/arm/
>   inflating: common/addon/Volume-Key-Selector/tools/arm/keycheck
>    creating: common/addon/Volume-Key-Selector/tools/x86/
>   inflating: common/addon/Volume-Key-Selector/tools/x86/keycheck
>   inflating: common/install.sh
>   inflating: customize.sh
>   inflating: module.prop
>   inflating: service.sh
>  
> - Running Addons -
>   Running Volume-Key-Selector...
> - Removing old files
> - Installing
> cat: can't open '/data/adb/modules_update/HideNavBar/Lang//1.txt': No such file or directory
> cat: can't open '/data/adb/modules_update/HideNavBar/Lang//2.txt': No such file or directory
> Volume key not detected. Try again
> Volume key not detected. Trying keycheck method
> cat: can't open '/data/adb/modules_update/HideNavBar/Lang//3.txt': No such file or directory
> cat: can't open '/data/adb/modules_update/HideNavBar/Lang//4.txt': No such file or directory
> Terminated
> cat: can't open '/data/adb/modules_update/HideNavBar/Lang//5.txt': No such file or directory
> Deleted 1 rows
> Deleted 1 rows
> find: /system/overlay: No such file or directory
> cp: can't stat '/data/adb/modules_update/HideNavBar/Mods/a/*': No such file or directory
> mv: can't rename '/data/adb/modules_update/HideNavBar/system/system/*': No such file or directory
>    Installing for arm SDK 30 device...
>  
> - Setting Permissions
> rmdir: '/data/adb/modules_update/HideNavBar': Directory not empty
> - Done
> ```
> 
> </details>

Try updating, released an update that should hopefully address this issue 

Oddly your device is returning no locality/language

**Comment by DanGLES3** [comment]
Proper fix should now be online, thx for your report

**Comment by lividhen** [comment]
Thanks! It _does_ work properly now.
