### ISSUE TITLE
Q: How do I change keyboard when I have Fullscreen enabled?

### ISSUE THREAD

**Issue by Balls0fSteel** [Magisk-Modules-Repo/HideNavBar#55]
First of all, I LOVE this module and I am very thankful for your work.

This is probably not an issue so please don't shoot me.
I checked all closed issues, the README, could not find an answer, so I thought I'll make an Issue (sorry!)

So the question is: **How do I change keyboards if I have the module in fullscreen?**

I use a Pixel 4a and a Oneplus 9R and neither has the option once I enable/use the module like this.
So I'm pretty much stuck with Gboard. Which works great 99% of the time, but rarely I need "Hacker keyboard" and such too.

Thank you!

**Comment by DanGLES3** [comment]
Pretty sure you can long press the spacebar on Gboard to switch keyboard's, not sure about jacket's keyboard however

**Comment by DanGLES3** [comment]
> First of all, I LOVE this module and I am very thankful for your work.
> 
> This is probably not an issue so please don't shoot me.
> I checked all closed issues, the README, could not find an answer, so I thought I'll make an Issue (sorry!)
> 
> So the question is: **How do I change keyboards if I have the module in fullscreen?**
> 
> I use a Pixel 4a and a Oneplus 9R and neither has the option once I enable/use the module like this.
> So I'm pretty much stuck with Gboard. Which works great 99% of the time, but rarely I need "Hacker keyboard" and such too.
> 
> Thank you!

Pretty sure you can long press the spacebar on Gboard to switch keyboard's, not sure about jacket's keyboard however

**Comment by Balls0fSteel** [comment]
Well, that workaround will definitely work, thank you very much!
