### ISSUE TITLE
immersive mode problem

### ISSUE THREAD

**Issue by crazyng6** [Magisk-Modules-Repo/HideNavBar#56]
pixel4xl
Rom:Android 12beta4.1
Immersive mode:The position of the navigation bar has moved down, making it easy to accidentally touch.

**Comment by DanGLES3** [comment]
> pixel4xl
> Rom:Android 12beta4.1
> Immersive mode:The position of the navigation bar has moved down, making it easy to accidentally touch.

mind providing a screenshot?  and what options did you select during installation?

**Comment by crazyng6** [comment]
![Screenshot_20210907-122225.png](https://user-images.githubusercontent.com/48212513/132284021-1bce836f-ef3d-4ea4-86f8-ce72197ed8d3.png)

**Comment by DanGLES3** [comment]
> pixel4xl
> Rom:Android 12beta4.1
> Immersive mode:The position of the navigation bar has moved down, making it easy to accidentally touch.

Could you be more specific? what do you mean by it having moved down? the navigation bar is still where it always was (as you can't really move the navigation bar up or down) it's now just invisible (so apps can draw behind it)

if it conflicting with apps is the problem well there is nothing i can about that, it's just the nature of hiding the navigation bar with gestures enabled (android will register gestures at the bottom part of the app)

**Comment by crazyng6** [comment]
> > pixel4xl
> > Rom:Android 12beta4.1
> > Immersive mode:The position of the navigation bar has moved down, making it easy to accidentally touch.
> 
> mind providing a screenshot?  and what options did you select during installation?

![Screenshot_20210907-122508.png](https://user-images.githubusercontent.com/48212513/132284397-fe548d56-07cf-4abe-9a21-0ed12dd38318.png)

**Comment by crazyng6** [comment]
> > pixel4xl
> > Rom:Android 12beta4.1
> > Immersive mode:The position of the navigation bar has moved down, making it easy to accidentally touch.
> 
> Could you be more specific? what do you mean by it having moved down? the navigation bar is still where it always was (as you can't really move the navigation bar up or down) it's now just invisible (so apps can draw behind it)
> 
> if it conflicting with apps is the problem well there is nothing i can about that, it's just the nature of hiding the navigation bar with gestures enabled (android will register gestures at the bottom part of the app)

I choose the immersive mode.But as what I mention,the search bar move down just as the fullscreen mode.

**Comment by DanGLES3** [comment]
> > > pixel4xl
> > > Rom:Android 12beta4.1
> > > Immersive mode:The position of the navigation bar has moved down, making it easy to accidentally touch.
> > 
> > 
> > Could you be more specific? what do you mean by it having moved down? the navigation bar is still where it always was (as you can't really move the navigation bar up or down) it's now just invisible (so apps can draw behind it)
> > if it conflicting with apps is the problem well there is nothing i can about that, it's just the nature of hiding the navigation bar with gestures enabled (android will register gestures at the bottom part of the app)
> 
> I choose the immersive mode.But as what I mention,the search bar move down just as the fullscreen mode.

it will move down regardless of mode, if it didn't you'd just have apps with blank?black spaces at the bottom (which would make the whole module pointless)

**Comment by crazyng6** [comment]
> > > > pixel4xl
> > > > Rom:Android 12beta4.1
> > > > Immersive mode:The position of the navigation bar has moved down, making it easy to accidentally touch.
> > > 
> > > 
> > > Could you be more specific? what do you mean by it having moved down? the navigation bar is still where it always was (as you can't really move the navigation bar up or down) it's now just invisible (so apps can draw behind it)
> > > if it conflicting with apps is the problem well there is nothing i can about that, it's just the nature of hiding the navigation bar with gestures enabled (android will register gestures at the bottom part of the app)
> > 
> > I choose the immersive mode.But as what I mention,the search bar move down just as the fullscreen mode.
> 
> it will move down regardless of mode, if it didn't you'd just have apps with blank/black spaces at the bottom, which would make the whole module pointless as you would not really gain any extra screen space (and apps would still have a bar at the bottom)

I understand.Big thanks for replying.Best regards.
