### ISSUE TITLE
Hide little close keyboard button

### ISSUE THREAD

**Issue by Vendicated** [Magisk-Modules-Repo/HideNavBar#59]
I got very annoyed by the space below the keyboard and this module fixed it, thanks a lot for that (working flawlessly on Oneplus 8t OxygenOs 11), but now the close keyboard button is right below my comma button so I keep pressing it accidently. it would be awesome if this module could hide the button completely, it is obsolete anyway since you can just use the back gesture to close it

**Comment by DanGLES3** [comment]
Unfortunately I've been yet to find a way to remove them as they seem to be made entirely in code with no resources I can edit to hide them

I'll try taking another look but can't promise anything

**Comment by Vendicated** [comment]
thats a bummer :(  Thanks anyway for the effort (and also for the fast reply 😮)

**Comment by DanGLES3** [comment]
> thats a bummer :(  Thanks anyway for the effort (and also for the fast reply 😮) 

Well I've got good news for ya, I've found a way, give me awhile and I'll send ya a version

**Comment by DanGLES3** [comment]
> thats a bummer :( Thanks anyway for the effort (and also for the fast reply 😮)

https://drive.google.com/file/d/1BZBBPW_CS1VYBwDOny8qYeVM_zZMnEMj/view?usp=drivesdk

Try this

**Comment by Vendicated** [comment]
Doesn't remove it for me sadly. Do I have to choose a specific option? 

I selected
- immersive
- hide pull yes
- reduce size yes
- sensitivity high
- disable back no

**Comment by DanGLES3** [comment]
> Doesn't remove it for me sadly. Do I have to choose a specific option? 
> 
> I selected
> - immersive
> - hide pull yes
> - reduce size yes
> - sensitivity high
> - disable back no

Mind showing me the module folder in data/adb/modules/hidenavbar/system/product/overlay?

**Comment by Vendicated** [comment]
![Screenshot_20210915-033502](https://user-images.githubusercontent.com/45497981/133356028-f6739857-a938-405f-88e3-b5b2d444de8f.jpg)

**Comment by DanGLES3** [comment]
> Doesn't remove it for me sadly. Do I have to choose a specific option? 
> 
> I selected
> - immersive
> - hide pull yes
> - reduce size yes
> - sensitivity high
> - disable back no

Try this

Idk why making functional systemui overlays is so annoying

**Comment by Vendicated** [comment]
still doesn't work
![Screenshot_20210915-034752](https://user-images.githubusercontent.com/45497981/133357104-a65e58da-815e-4ed1-b489-dd1a5f98241f.jpg)

**Comment by DanGLES3** [comment]
> Doesn't remove it for me sadly. Do I have to choose a specific option? 
> 
> I selected
> - immersive
> - hide pull yes
> - reduce size yes
> - sensitivity high
> - disable back no

I've had goofed up, here it is

https://drive.google.com/file/d/1BvWwfYnf1Hjx6sLZqgGVX93kM3hYyIPA/view?usp=drivesdk

**Comment by DanGLES3** [comment]
> Doesn't remove it for me sadly. Do I have to choose a specific option? 
> 
> I selected
> - immersive
> - hide pull yes
> - reduce size yes
> - sensitivity high
> - disable back no

Try the new I've sent, I've messed up the old overlay, it was conflicting with the pill hide one

**Comment by Vendicated** [comment]
Not working still

**Comment by DanGLES3** [comment]
> Not working still

Run the following command on a root terminal and show me the results under systemui

cmd overlay list 

Idk why it's so hard making systemui overlays

**Comment by DanGLES3** [comment]
> Not working still

Don't give up yet, I just need to make an overlay that works 

If you wish to try this later or tomorrow if you don't have the time that's fair enough

**Comment by Vendicated** [comment]
sorry I misclicked lol
https://gist.github.com/Vendicated/80fbcd2e06e2edfbdf1be4d9b74c3399

**Comment by DanGLES3** [comment]
> Not working still

For now you can use this hacked up Substratum theme I've just made 

https://drive.google.com/file/d/1BwhEMCv0oDDIdCCU3ReHjsTcIg_30lZg/view?usp=drivesdk

**Comment by DanGLES3** [comment]
> Not working still

For now you can try this hacked up Substratum theme I've just made 

https://drive.google.com/file/d/1BwhEMCv0oDDIdCCU3ReHjsTcIg_30lZg/view?usp=drivesdk

**Comment by Vendicated** [comment]
```
» [com.android.systemui]: ERROR: resource directory '/data/user/0/projekt.substratum/cache/SubstratumBuilder//res/' does not exist
» [com.android.systemui]: Installation of "com.android.systemui" has failed.```

**Comment by Vendicated** [comment]
ah it works on lite. and now it really is gone 👀 thanks a lot you are awesome :)

**Comment by DanGLES3** [comment]
> ah it works on lite. and now it really is gone 👀 thanks a lot you are awesome :)

Great, I'm on my PC now, I'll see if I can make a functional overlay that I can put in my module

**Comment by DanGLES3** [comment]
> ah it works on lite. and now it really is gone  thanks a lot you are awesome :)

OK, interesting find, my previous overlays were not only wrong (winrar cache or some stuff like that) but they were totally broken lmfao

https://drive.google.com/file/d/1iL_2qxcJ317zHDRlpGoGF5oCJqvk-V4y/view?usp=sharing

this should work

**Comment by DanGLES3** [comment]
> ah it works on lite. and now it really is gone  thanks a lot you are awesome :)

https://drive.google.com/file/d/1dGkTjsoPFvxpUYFJ-iMqHcS2SrYBthLz/view?usp=sharing

This should work, i've messed up my previous overlays, disable the substratum overlay before trying

**Comment by Vendicated** [comment]
yep, it's working now! and don't worry I don't mind

**Comment by DanGLES3** [comment]
> yep, it's working now! and don't worry I don't mind

just making sure, u disabled the substratum overlay prior to installing the module and rebooting correct?

**Comment by Vendicated** [comment]
yes, the substratum theme is no longer applied

**Comment by DanGLES3** [comment]
> yes, the substratum theme is no longer applied

Great, thanks a lot for helping me on testing this

**Comment by DanGLES3** [comment]
> yes, the substratum theme is no longer applied

https://drive.google.com/file/d/14xedvz0KOYC8ZTXon3zACFfbjSiGjNJc/view?usp=sharing

Here's the with that as an separate option if you wish to test it out for me

**Comment by DanGLES3** [comment]
> yes, the substratum theme is no longer applied

the update is already up if you wish to test it

**Comment by Vendicated** [comment]
sorry I didn't see this until now. works wonderfully thank you very much!!
