### ISSUE TITLE
 Snapchat Bug

### ISSUE THREAD

**Issue by roman-ta27** [Magisk-Modules-Repo/HideNavBar#7]
On my Xiaomi Mi 9 Cepheus (Running Paranoid Android Quartz 2 AOSP ROM) Snapchat has a black bar at the bottom of the display.
Has anyone else experienced this?
![Screenshot_20200501-144246](https://user-images.githubusercontent.com/64643890/80806371-c8f68b00-8bba-11ea-8acb-06b456cd1854.jpg)
Also visible in my recents:
![Screenshot_20200501-202117](https://user-images.githubusercontent.com/64643890/80830589-813b2800-8be9-11ea-9553-55a78bc9d613.jpg)

**Comment by DanGLES3** [comment]
try cleaning the app's data, i've seen some apps which do not adjust automatically and require clearing their data to fix
