### ISSUE TITLE
Android 12L developer preview not supported

### ISSUE THREAD

**Issue by leifalbor** [Magisk-Modules-Repo/HideNavBar#73]
Any plans to support system API v32?

**Comment by leifalbor** [comment]
Worth noting - I forked and edited customize.sh to allow MAXAPI=32, works like a charm 🙂

**Comment by DanGLES3** [comment]
> Worth noting - I forked and edited customize.sh to allow MAXAPI=32, works like a charm 🙂

Thx for the heads-up and apologies taking so long to respond, sadly the official Magisk repository has shutdown the ability for modules to release updates, so if you wish to get updates on my module I'd either recommend going to my Telegram channel or going to the Androidacy website

**Comment by leifalbor** [comment]
All good dude!  Personally I jumped over to Fox's Magisk Module Manager.  It pulls downloads both from this archived repo and their own repo at https://github.com/orgs/Magisk-Modules-Alt-Repo/
Handy for it's ability to update modules without having to do so manually.  Will check out Androidacy though!
