### ISSUE TITLE
A small problem

### ISSUE THREAD

**Issue by Oopas** [Magisk-Modules-Repo/HideNavBar#76]
Can I make the color of this part the same as the Gboard 😁

**Comment by Oopas** [comment]
![Uploading 2.jpg…]()

**Comment by Oopas** [comment]
![Uploading 2.jpg…]()

**Comment by Oopas** [comment]
![2](https://user-images.githubusercontent.com/69417818/154841597-36acfe50-5b62-4a37-b701-dfef46a83073.jpg)

**Comment by DanGLES3** [comment]
> ![2](https://user-images.githubusercontent.com/69417818/154841597-36acfe50-5b62-4a37-b701-dfef46a83073.jpg)

This is technically related to Gboard, it has blocked navbar coloring to Google devices only and requires a module to spoof them, however spoofing on a stock ROM could cause issues 

https://t.me/gboardthemes/268015

**Comment by Oopas** [comment]
> > ![2](https://user-images.githubusercontent.com/69417818/154841597-36acfe50-5b62-4a37-b701-dfef46a83073.jpg)
> 
> This is technically related to Gboard, it has blocked navbar coloring to Google devices only and requires a module to spoof them, however spoofing on a stock ROM could cause issues
> 
> https://t.me/gboardthemes/268015

It works very well, thanks!
