### ISSUE TITLE
Can the gesture height be even lower ?

### ISSUE THREAD

**Issue by EricwanAR** [Magisk-Modules-Repo/HideNavBar#8]
The module is great, but gesture is too sensitive. Every time I move the pushing button at the bottom of the screen (when using Snapseed for example)it would trigger the app switch gesture.
I modded the module myself by changing the gesture height from 23dp to 18dp and it works perfect for me. I wonder if you can make the value as default

**Comment by DanGLES3** [comment]
I will consider, i need to do some tests to see if lowering this much doesn't create any issues

**Comment by hani4k** [comment]
> works

Can you send your version?

**Comment by hani4k** [comment]
Can i get your version?

**Comment by EricwanAR** [comment]
> > works
> 
> Can you send your version?

https://drive.google.com/file/d/14cnj-YdaeQ-W1i9nX3yYQ9nwif30Ed-C/view?usp=drivesdk

I only modified Q related files so this won't work for R

**Comment by hani4k** [comment]
I'm using Android Q. But what's the difference?

**Comment by DanGLES3** [comment]
> I'm using Android Q. But what's the difference?

Android R needs a special overlay that needs to target it and be signed using the signature scheme V2, Android R refuses system APKs that aren't signed using that signature scheme, for Android Q the overlays are simply signed using a testkey (since Q does not enforce the signature scheme V2) and it's overall easier to work with them

i can easily update the Pie overlays on my phone, but the R overlays needs to be modified on Android studio in order to be signed with the new signature scheme

**Comment by hani4k** [comment]
> > > works
> > 
> > Can you send your version?
> 
> https://drive.google.com/file/d/14cnj-YdaeQ-W1i9nX3yYQ9nwif30Ed-C/view?usp=drivesdk
> 
> I only modified Q related files so this won't work for R

What's the difference between your mode and the original one? And why? 🙂

**Comment by EricwanAR** [comment]
> > > > works
> > > 
> > > 
> > > Can you send your version?
> > 
> > 
> > https://drive.google.com/file/d/14cnj-YdaeQ-W1i9nX3yYQ9nwif30Ed-C/view?usp=drivesdk
> > I only modified Q related files so this won't work for R
> 
> What's the difference between your mode and the original one? And why?

well, as I said above, I lower the gesture triggering area from 23dp to 18dp, which is less likely to trigger the app switch gesture. 
I do this because I can't easily drag the elements at the bottom of the screen with the original module setting

**Comment by DanGLES3** [comment]
> The module is great, but gesture is too sensitive. Every time I move the pushing button at the bottom of the screen (when using Snapseed for example)it would trigger the app switch gesture.
> I modded the module myself by changing the gesture height from 23dp to 18dp and it works perfect for me. I wonder if you can make the value as default

how's triggering the actual gestures? is it still as reliable? i'm worried that lowering it too much can cause the gestures to become unreliable to trigger

**Comment by EricwanAR** [comment]
> > The module is great, but gesture is too sensitive. Every time I move the pushing button at the bottom of the screen (when using Snapseed for example)it would trigger the app switch gesture.
> > I modded the module myself by changing the gesture height from 23dp to 18dp and it works perfect for me. I wonder if you can make the value as default
> 
> how's triggering the actual gestures? is it still as reliable? i'm worried that lowering it too much can cause the gestures to become unreliable to trigger

it works quite fine for me anyway, gesture is still reliable. Since I'm using it on a non-full-screen device with higher chinbar , I think somewhere around 20dp might be a better choice for everyone

**Comment by DanGLES3** [comment]
> The module is great, but gesture is too sensitive. Every time I move the pushing button at the bottom of the screen (when using Snapseed for example)it would trigger the app switch gesture.
> I modded the module myself by changing the gesture height from 23dp to 18dp and it works perfect for me. I wonder if you can make the value as default

Ok, after some testing it seems 18dp is a good enough value for both fullscreen and now fullscreen devices, i'll update the module as soon as possible

**Comment by DanGLES3** [comment]
> > > works
> > 
> > 
> > Can you send your version?
> 
> https://drive.google.com/file/d/14cnj-YdaeQ-W1i9nX3yYQ9nwif30Ed-C/view?usp=drivesdk
> 
> I only modified Q related files so this won't work for R

btw, did you mod all Q overlays?

**Comment by DanGLES3** [comment]
the update should already be avalible, thank you very much for the suggestions

**Comment by EricwanAR** [comment]
> the update should already be available, thank you very much for the suggestion

thank you very much for you work
