### ISSUE TITLE
Camera slow changing modes with module installed on Pixel 6

### ISSUE THREAD

**Issue by Displema** [Magisk-Modules-Repo/HideNavBar#84]
I was wondering why on my Pixel 6 changing camera mode took about 1-2 seconds, whereas without root it was immediate. I tried unistalling this module and the camera started working flawlessly. I'm running the latest update on my Pixel 6, latest Magisk (24.3), and the latest version of HideNavBar.

**Comment by DanGLES3** [comment]
> I was wondering why on my Pixel 6 changing camera mode took about 1-2 seconds, whereas without root it was immediate. I tried unistalling this module and the camera started working flawlessly. I'm running the latest update on my Pixel 6, latest Magisk (24.3), and the latest version of HideNavBar.

That's a side effect of fully hiding the navbar, using the terminal configuration tool to set the navbar and keyboard bar to 1.0 will prevent the issue but it might make the navbar ever so slightly visible

Nothing much i can do, that's a Google thing
