### ISSUE TITLE
Huge black bar under keyboard

### ISSUE THREAD

**Issue by OCDino** [Magisk-Modules-Repo/HideNavBar#9]
hey! I wanna start off saying I'm super thankful for this module because I HATE the gesture pills. I read other people saying that the keyboard is too low but I'm having the exact opposite problem. After an update to the ROM on my phone, there's now a huge black bar at the bottom of my screen (down in the screenshot) which puts the keyboard way higher than I'm used to and I don't know how to get it to go away. 

![Screenshot_Chrome_20200518-211125](https://user-images.githubusercontent.com/65577165/82273865-9be10100-994c-11ea-8060-b58f727b50ff.png)

**Comment by DanGLES3** [comment]
tried reinstalling my module perhaps? or maybe toggling gestures off and on?

**Comment by OCDino** [comment]
I did both but I still have it :/ I think I'll just learn to live with it.

**Comment by DanGLES3** [comment]
> I did both but I still have it :/ I think I'll just learn to live with it.

what ROM are you using?
