### ISSUE TITLE
Facebook Messenger huge gap issue

### ISSUE THREAD

**Issue by MaestroAR** [Magisk-Modules-Repo/HideNavBar#93]
![Screenshot_20220903-180614_Messenger__01](https://user-images.githubusercontent.com/93711053/188265904-7b656028-b516-4613-810e-130083dd14a4.png)

**Comment by DanGLVK** [comment]
> ![Screenshot_20220903-180614_Messenger__01](https://user-images.githubusercontent.com/93711053/188265904-7b656028-b516-4613-810e-130083dd14a4.png)

Mind specifying device? Android version? Options chosen during install?

**Comment by MaestroAR** [comment]
> 

It's fine now. I didn't use Termux the first time. I just installed it via FoxMM
