### ISSUE TITLE
Doesn't support 64 bit only

### ISSUE THREAD

**Issue by dd805bb** [Magisk-Modules-Repo/HideNavBar#94]
Android 13 Pixel 7 Pro
Failed to install, says it does not support 64 bit only systems.

**Comment by DanGLVK** [comment]
> Android 13 Pixel 7 Pro Failed to install, says it does not support 64 bit only systems.

Try installing the zip from the Magisk app instead 
[Immersive-Gestures-(QT)_v21.0_(55).zip](https://github.com/Magisk-Modules-Repo/HideNavBar/files/9906704/Immersive-Gestures-.QT._v21.0_.55.zip)

**Comment by dd805bb** [comment]
Worked perfectly.
