### ISSUE TITLE
64bit system 

### ISSUE THREAD

**Issue by alabotski** [Magisk-Modules-Repo/HideNavBar#96]
Hi

I tried use this module on my Google Pixel 7 Pro but has error

![Screenshot_20221121-211518](https://user-images.githubusercontent.com/439337/203143262-d83cc2fa-3d4c-42c1-9fba-52c2259678b3.png)

**Comment by DanGLVK** [comment]
> Hi
> 
> I tried use this module on my Google Pixel 7 Pro but has error
> 
> ![Screenshot_20221121-211518](https://user-images.githubusercontent.com/439337/203143262-d83cc2fa-3d4c-42c1-9fba-52c2259678b3.png)

Install the zip through Magisk, this issue is due to something on Fox Module manager 

https://github.com/Magisk-Modules-Alt-Repo/HideNavBar/releases/download/v21/Fullscreen-Immersive.Gestures-.Q-T.-v21.0-.54.zip

**Comment by alabotski** [comment]
@DanGLES3 thanks all work fine
