### ISSUE TITLE
Module crashes WebView in settings

### ISSUE THREAD

**Issue by gjf** [Magisk-Modules-Repo/HideNavBar#98]
Latest version of FullScreenImmersive from MMM.
Oneplus 7T Pro, latest stock Android 12 firmware.
Enabling this module leads to disappearing of WebView service in settings.
Have to remove the module to get it back. Though disabling module also help.

**Comment by DanGLVK** [comment]
> Latest version of FullScreenImmersive from MMM. Oneplus 7T Pro, latest stock Android 12 firmware. Enabling this module leads to disappearing of WebView service in settings. Have to remove the module to get it back. Though disabling module also help.

Then your ROM is oddly rejecting third party fabricated overlays (first time i've ever seen that), you could try the substratum version of the module on Substratum Lite as it should be way more reliable (after installing the APK, choose the options you want on Substratum Lite, tap create overlays, reboot, then enable them on the app)

[FSIM-Version-1.zip](https://github.com/Magisk-Modules-Repo/HideNavBar/files/10448268/FSIM-Version-1.zip)

**Comment by gjf** [comment]
Thanks but I spent too much time already to identify the source of problem. No time and no real need to install something and check again.
Hope other users will be informed about issue.
