### ISSUE TITLE
Module not working

### ISSUE THREAD

**Issue by Ankit2502** [Magisk-Modules-Repo/HideNavBar#99]
I am on Evo x gsi and using pixel launcher extended on Android 13, I want to get rid of pill as well as spacing below keyboard so I installed this module and selected full screen but it simply just doesn't work.. 
Pill is still their as well as space below keyboard doesn't get reduce, hope you wil see to it and fix it as soon as posible as It is realy hard to use phone with all that space below keyboard

**Comment by DanGLVK** [comment]
> I am on Evo x gsi and using pixel launcher extended on Android 13, I want to get rid of pill as well as spacing below keyboard so I installed this module and selected full screen but it simply just doesn't work.. Pill is still their as well as space below keyboard doesn't get reduce, hope you wil see to it and fix it as soon as posible as It is realy hard to use phone with all that space below keyboard

What version of the module did you install? Just want be sure, be specific of the version number

**Comment by Ankit2502** [comment]
> > I am on Evo x gsi and using pixel launcher extended on Android 13, I want to get rid of pill as well as spacing below keyboard so I installed this module and selected full screen but it simply just doesn't work.. Pill is still their as well as space below keyboard doesn't get reduce, hope you wil see to it and fix it as soon as posible as It is realy hard to use phone with all that space below keyboard
> 
> What version of the module did you install? Just want be sure, be specific of the version number


Sorry for late reply my device wasn't with me for long time...
I tried the latest version only available v13.0. Even you can try that too on any aosp.. I tired it on pixel experience and lineage too it doesn't work...
+ I use tab for this testing and that new floating taskbar feature for Android 12+ was enabled

Like this module is flashed on ful screen still space is there
![Screenshot_2023-09-23-03-51-44-474_com google android apps photos](https://github.com/Magisk-Modules-Repo/HideNavBar/assets/89592455/0b71315d-ac6b-4a6d-ba7d-0ada2641a7ab)

And floating taskbar I was taking about is this
![Screenshot_2023-09-23-03-52-10-203_com google android apps photos](https://github.com/Magisk-Modules-Repo/HideNavBar/assets/89592455/87db2d8e-9331-4ad7-9ff4-586fb65cc0b1)

**Comment by DanGLVK** [comment]
> > > I am on Evo x gsi and using pixel launcher extended on Android 13, I want to get rid of pill as well as spacing below keyboard so I installed this module and selected full screen but it simply just doesn't work.. Pill is still their as well as space below keyboard doesn't get reduce, hope you wil see to it and fix it as soon as posible as It is realy hard to use phone with all that space below keyboard
> > 
> > 
> > What version of the module did you install? Just want be sure, be specific of the version number
> 
> Sorry for late reply my device wasn't with me for long time... I tried the latest version only available v13.0. Even you can try that too on any aosp.. I tired it on pixel experience and lineage too it doesn't work...
> 
> * I use tab for this testing and that new floating taskbar feature for Android 12+ was enabled
> 
> Like this module is flashed on ful screen still space is there ![Screenshot_2023-09-23-03-51-44-474_com google android apps photos](https://user-images.githubusercontent.com/89592455/270067834-0b71315d-ac6b-4a6d-ba7d-0ada2641a7ab.jpg)
> 
> And floating taskbar I was taking about is this ![Screenshot_2023-09-23-03-52-10-203_com google android apps photos](https://user-images.githubusercontent.com/89592455/270067872-87db2d8e-9331-4ad7-9ff4-586fb65cc0b1.jpg)

v13 is not the latest available version, https://github.com/Magisk-Modules-Alt-Repo/HideNavBar/releases

As stated in the module's readme in the first lines, I've stopped updating the module in the official repo as it was no longer supported by Magisk, so it's now on the alt repo

**Comment by Ankit2502** [comment]
Am sorry, i download the module from telegram channel of modules repository so I just clicked link and download file didn't go through the post, will try that alt one and report if issue exist or not...
Thanks for your help...
